import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Fluent theme generated by Launcher.
class AppTheme {
  static const Color accent = Color(0xFF1DB954);

  /// Applied via [ThemeData.fontFamily] to avoid TextTheme type clashes
  /// between google_fonts and Flutter on some Windows builds.
  static String? get _fontFamily => GoogleFonts.lexend().fontFamily;

  static const Color backgroundDark = Color(0xFF202020);
  static const Color surfaceDark = Color(0xFF2C2C2C);
  static const Color cardDark = Color(0xFF323232);
  static const Color backgroundLight = Color(0xFFF3F3F3);
  static const Color surfaceLight = Color(0xFFFFFFFF);
  static const double _r = 8;

  static ThemeData get light => ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        colorScheme: ColorScheme.light(
          primary: accent,
          onPrimary: _onAccent,
          secondary: accent,
          surface: surfaceLight,
          onSurface: const Color(0xFF1A1A1A),
          outline: const Color(0xFFE5E5E5),
        ),
        scaffoldBackgroundColor: backgroundLight,
        fontFamily: _fontFamily,
        dividerTheme: const DividerThemeData(color: Color(0xFFE5E5E5)),
        cardTheme: CardThemeData(
          color: surfaceLight,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(_r),
            side: const BorderSide(color: Color(0xFFE5E5E5)),
          ),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xF2F3F3F3),
          foregroundColor: Color(0xFF1A1A1A),
          elevation: 0,
          scrolledUnderElevation: 0,
          surfaceTintColor: Colors.transparent,
        ),
        navigationBarTheme: NavigationBarThemeData(
          backgroundColor: surfaceLight,
          indicatorColor: accent.withValues(alpha: 0.15),
          indicatorShape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(_r),
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: accent,
            foregroundColor: _onAccent,
            elevation: 0,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(_r),
            ),
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: const Color(0xFF1A1A1A),
            side: const BorderSide(color: Color(0xFFD1D1D1)),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(_r),
            ),
          ),
        ),
        filledButtonTheme: FilledButtonThemeData(
          style: FilledButton.styleFrom(
            backgroundColor: accent,
            foregroundColor: _onAccent,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(_r),
            ),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: surfaceLight,
          contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(_r),
            borderSide: const BorderSide(color: Color(0xFFD1D1D1)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(_r),
            borderSide: const BorderSide(color: Color(0xFFD1D1D1)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(_r),
            borderSide: BorderSide(color: accent, width: 2),
          ),
        ),
        dialogTheme: DialogThemeData(
          backgroundColor: surfaceLight,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      );

  static ThemeData get dark => ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorScheme: ColorScheme.dark(
          primary: accent,
          onPrimary: _onAccent,
          secondary: accent,
          surface: surfaceDark,
          onSurface: const Color(0xFFF3F3F3),
          outline: const Color(0xFF3F3F3F),
        ),
        scaffoldBackgroundColor: backgroundDark,
        fontFamily: _fontFamily,
        dividerTheme: const DividerThemeData(color: Color(0xFF3F3F3F)),
        cardTheme: CardThemeData(
          color: cardDark,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(_r),
            side: const BorderSide(color: Color(0xFF3F3F3F)),
          ),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xF2202020),
          foregroundColor: Color(0xFFF3F3F3),
          elevation: 0,
          scrolledUnderElevation: 0,
          surfaceTintColor: Colors.transparent,
        ),
        navigationBarTheme: NavigationBarThemeData(
          backgroundColor: surfaceDark,
          indicatorColor: accent.withValues(alpha: 0.2),
          indicatorShape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(_r),
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: accent,
            foregroundColor: _onAccent,
            elevation: 0,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(_r),
            ),
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: const Color(0xFFF3F3F3),
            side: const BorderSide(color: Color(0xFF5C5C5C)),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(_r),
            ),
          ),
        ),
        filledButtonTheme: FilledButtonThemeData(
          style: FilledButton.styleFrom(
            backgroundColor: accent,
            foregroundColor: _onAccent,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(_r),
            ),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: cardDark,
          contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(_r),
            borderSide: const BorderSide(color: Color(0xFF5C5C5C)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(_r),
            borderSide: const BorderSide(color: Color(0xFF5C5C5C)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(_r),
            borderSide: BorderSide(color: accent, width: 2),
          ),
        ),
        dialogTheme: DialogThemeData(
          backgroundColor: cardDark,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      );


  static Color get _onAccent =>
      accent.computeLuminance() > 0.5 ? Colors.black : Colors.white;
}
